"""Payment intents — Pakistani gateway checkouts

Revision ID: 0015
Revises: 0014
Create Date: 2026-05-15

Phase 5 Step 73: Pakistani payment-gateway plumbing.

Each subscription purchase creates a `payment_intents` row that tracks
the gateway round-trip: JazzCash / Easypaisa / Meezan IPG / Allied via
1LINK PayFast / SafePay. The provider's checkout URL is generated by
our backend (HMAC-signed for redirect gateways, REST-call for API
gateways), then the user is sent there. On return, the gateway POSTs to
our callback endpoint, we verify the signature, and on success we
flip the matching `user_subscriptions` row to `active`.

Why this table instead of stuffing it into user_subscriptions?
- Multiple intents per subscription (retry, cancel, upgrade) — keep
  the audit trail.
- Each provider has its own response shape; storing as JSONB is the
  honest way to handle that without a 30-column wide table.
- Reconciliation: when accounting asks "where's this PKR 900?" we
  walk this table by gateway txn ref → user → plan.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "payment_intents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "plan_id",
            sa.Integer(),
            sa.ForeignKey("subscription_plans.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(40), nullable=False),
        sa.Column("billing_cycle", sa.String(10), nullable=False, server_default="monthly"),
        sa.Column("amount_pkr", sa.Numeric(10, 2), nullable=False),
        # pending → redirected → paid | failed | canceled | expired
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        # Our merchant-side ref (what we send to gateway as "txn ref"). Unique so
        # a retry of the same intent doesn't clash; we generate a new intent
        # row for each retry.
        sa.Column("merchant_txn_ref", sa.String(60), nullable=False),
        # Whatever the gateway returns as its own canonical ID (JazzCash
        # pp_TxnRefNo, Easypaisa orderRefNum, PayFast transaction_id, etc.)
        sa.Column("gateway_txn_id", sa.String(120), nullable=True),
        sa.Column(
            "request_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "response_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("checkout_url", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("returned_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "expires_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_txn_ref", name="uq_payment_intents_merchant_ref"),
        sa.CheckConstraint(
            "status IN ('pending', 'redirected', 'paid', 'failed', 'canceled', 'expired')",
            name="ck_payment_intents_status",
        ),
        sa.CheckConstraint(
            "billing_cycle IN ('monthly', 'annual')",
            name="ck_payment_intents_cycle",
        ),
        sa.CheckConstraint(
            "provider IN ("
            "'jazzcash', 'easypaisa', 'meezan', 'allied_payfast', "
            "'safepay', 'nayapay', 'manual'"
            ")",
            name="ck_payment_intents_provider",
        ),
    )
    op.create_index(
        "ix_payment_intents_user_status",
        "payment_intents",
        ["user_id", "status"],
    )
    op.create_index(
        "ix_payment_intents_gateway_txn",
        "payment_intents",
        ["provider", "gateway_txn_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_payment_intents_gateway_txn", table_name="payment_intents")
    op.drop_index("ix_payment_intents_user_status", table_name="payment_intents")
    op.drop_table("payment_intents")
